watchers: [
  {
    tokenSymbol: loom,
    tokenAddress: '0xa4e8c3ec456107ea67d3075bf9e3df3a75823db0',
    orderType: sell,
    operationOn: token,
    amount: 1,
    conditions: [
      {
        operation: gt,
        outputAmount: 0.0024
      }
    ]
  },
  {
    tokenSymbol: lpt,
    tokenAddress: '0x58b6a8a3302369daec383334672404ee733ab239',
    orderType: sell,
    operationOn: token,
    amount: 1,
    conditions: [
      {
        operation: gt,
        outputAmount: 0.000023881
      }
    ]
  },
  {
    tokenSymbol: OCEAN,
    tokenAddress: '0xb9E52bC9C8F39AE354154130D861cBA010e7Cd7f',
    orderType: sell,
    operationOn: token,
    amount: 1,
    conditions: [
      {
        operation: gt,
        outputAmount: 0.000091
      }
    ]
  }
]