export default {
    CREATE_BUY_ORDERS : 'CREATE_BUY_ORDERS',
    CREATE_SELL_ORDERS : 'CREATE_SELL_ORDERS',
    UPDATE_BUY_ORDER : 'UPDATE_BUY_ORDER',
    REMOVE_BUY_ORDER : 'REMOVE_BUY_ORDER',
    ADD_BUY_ORDER : 'ADD_BUY_ORDER',
    UPDATE_SELL_ORDER : 'UPDATE_SELL_ORDER',
    REMOVE_SELL_ORDER : 'REMOVE_SELL_ORDER',
    ADD_SELL_ORDER : 'ADD_SELL_ORDER',
    UPDATE_CURRENT_SEQ: 'UPDATE_CURRENT_SEQ'
}